
package com.magicpigeon.demo.pi.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "dbDemo_ptt-bindingQSService",
                  targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/ActiveWaitingSB/DemoSB/dbDemo",
                  wsdlLocation =
                  "http://localhost:7101/DemoSB/DemoPS?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fpcbpel%2Fadapter%2Fdb%2FActiveWaitingSB%2FDemoSB%2FdbDemo%7DdbDemo_ptt-bindingQSService")
public class DbDemoPttBindingQSService extends Service {

    private final static URL DBDEMOPTTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DBDEMOPTTBINDINGQSSERVICE_EXCEPTION;
    private final static QName DBDEMOPTTBINDINGQSSERVICE_QNAME =
        new QName("http://xmlns.oracle.com/pcbpel/adapter/db/ActiveWaitingSB/DemoSB/dbDemo",
                  "dbDemo_ptt-bindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://localhost:7101/DemoSB/DemoPS?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fpcbpel%2Fadapter%2Fdb%2FActiveWaitingSB%2FDemoSB%2FdbDemo%7DdbDemo_ptt-bindingQSService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DBDEMOPTTBINDINGQSSERVICE_WSDL_LOCATION = url;
        DBDEMOPTTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public DbDemoPttBindingQSService() {
        super(__getWsdlLocation(), DBDEMOPTTBINDINGQSSERVICE_QNAME);
    }

    public DbDemoPttBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DBDEMOPTTBINDINGQSSERVICE_QNAME, features);
    }

    public DbDemoPttBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, DBDEMOPTTBINDINGQSSERVICE_QNAME);
    }

    public DbDemoPttBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DBDEMOPTTBINDINGQSSERVICE_QNAME, features);
    }

    public DbDemoPttBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DbDemoPttBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DbDemoPtt
     */
    @WebEndpoint(name = "dbDemo_ptt-bindingQSPort")
    public DbDemoPtt getDbDemoPttBindingQSPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/ActiveWaitingSB/DemoSB/dbDemo",
                                       "dbDemo_ptt-bindingQSPort"), DbDemoPtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DbDemoPtt
     */
    @WebEndpoint(name = "dbDemo_ptt-bindingQSPort")
    public DbDemoPtt getDbDemoPttBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/ActiveWaitingSB/DemoSB/dbDemo",
                                       "dbDemo_ptt-bindingQSPort"), DbDemoPtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DBDEMOPTTBINDINGQSSERVICE_EXCEPTION != null) {
            throw DBDEMOPTTBINDINGQSSERVICE_EXCEPTION;
        }
        return DBDEMOPTTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
