package com.magicpigeon.demo.pi.client;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class dbDemo_pttBindingQSPortClient {
    public static void main(String[] args) {
        DbDemoPttBindingQSService dbDemoPttBindingQSService = new DbDemoPttBindingQSService();
        DbDemoPtt dbDemoPtt = dbDemoPttBindingQSService.getDbDemoPttBindingQSPort();
        // Add your code to call the desired methods.
        // TODO: Test Methods

    }
}
