
package com.magicpigeon.demo.pi.client;

import com.magicpigeon.demo.pi.client.types.DbDemoSelectCustomId;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.magicpigeon.demo.pi.client.types.CustomProcessInfoCollection;
import com.magicpigeon.demo.pi.client.types.CustomProcessInfoPrimaryKey;
import com.magicpigeon.demo.pi.client.types.DbDemoSelect;
import com.magicpigeon.demo.pi.client.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "dbDemo_ptt",
            targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/ActiveWaitingSB/DemoSB/dbDemo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface DbDemoPtt {


    /**
     *
     * @param customProcessInfoCollection
     */
    @WebMethod(action = "merge")
    @Oneway
    public void merge(@WebParam(name = "CustomProcessInfoCollection",
                                targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/dbDemo",
                                partName = "CustomProcessInfoCollection")
                      CustomProcessInfoCollection customProcessInfoCollection);

    /**
     *
     * @param customProcessInfoCollection
     */
    @WebMethod(action = "insert")
    @Oneway
    public void insert(@WebParam(name = "CustomProcessInfoCollection",
                                 targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/dbDemo",
                                 partName = "CustomProcessInfoCollection")
                       CustomProcessInfoCollection customProcessInfoCollection);

    /**
     *
     * @param dbDemoSelectInputParameters
     * @return
     *     returns com.magicpigeon.demo.pi.client.types.CustomProcessInfoCollection
     */
    @WebMethod(action = "dbDemoSelect")
    @WebResult(name = "CustomProcessInfoCollection",
               targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/dbDemo",
               partName = "CustomProcessInfoCollection")
    public CustomProcessInfoCollection dbDemoSelect(@WebParam(name = "dbDemoSelectInputParameters",
                                                              targetNamespace =
                                                              "http://xmlns.oracle.com/pcbpel/adapter/db/top/dbDemo",
                                                              partName = "dbDemoSelect_inputParameters")
                                                    DbDemoSelectCustomId dbDemoSelectInputParameters);

    /**
     *
     * @param selectByPrimaryKeyInputParameters
     * @return
     *     returns com.magicpigeon.demo.pi.client.types.CustomProcessInfoCollection
     */
    @WebMethod(action = "selectByPrimaryKey")
    @WebResult(name = "CustomProcessInfoCollection",
               targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/dbDemo",
               partName = "CustomProcessInfoCollection")
    public CustomProcessInfoCollection selectByPrimaryKey(@WebParam(name = "CustomProcessInfoPrimaryKey",
                                                                    targetNamespace =
                                                                    "http://xmlns.oracle.com/pcbpel/adapter/db/top/dbDemo",
                                                                    partName = "selectByPrimaryKey_inputParameters")
                                                          CustomProcessInfoPrimaryKey selectByPrimaryKeyInputParameters);

}
