
package com.magicpigeon.demo.bpm.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

import com.magicpigeon.demo.bpm.client.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "DemoPortType", targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/Demo")
@XmlSeeAlso({ ObjectFactory.class })
public interface DemoPortType {


    /**
     *
     * @param customId
     */
    @WebMethod(action = "start")
    @Oneway
    @RequestWrapper(localName = "start", targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/Demo",
                    className = "com.magicpigeon.demo.bpm.client.types.Start")
    public void start(@WebParam(name = "customId", targetNamespace = "") String customId);

}
