CREATE TABLE DEMO.CUSTOM_PROCESS_INFO 
(
  CUSTOM_ID VARCHAR2(255 BYTE) 
, INSTANCE_NUMBER NUMBER(20, 2) 
, INSTANCE_ID VARCHAR2(255 BYTE) NOT NULL 
, COMPOSITE_NAME VARCHAR2(255 BYTE) 
, COMPOSITE_DN VARCHAR2(255 BYTE) 
, COMPOSITE_LABEL VARCHAR2(255 BYTE) 
, COMPOSITE_REVISION VARCHAR2(255 BYTE) 
, COMPOSITE_INSTANCE_ID VARCHAR2(255 BYTE) 
, PROCESS_DN VARCHAR2(255 BYTE) 
, ACTIVITY_NAME VARCHAR2(255 BYTE) 
, CONSTRAINT CUSTOM_PROCESS_INFO_PK PRIMARY KEY 
  (
    INSTANCE_ID 
  )
  ENABLE 
);