-- Script for creation of the DEMO Schema --

CREATE TABLESPACE "DEMODAT" LOGGING
DATAFILE 'DEMODAT.dbf' SIZE 512M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE "DEMOTMP"
TEMPFILE 'DEMOTMP.dbf' SIZE 256M
AUTOEXTEND ON;

CREATE USER "DEMO" PROFILE "DEFAULT" IDENTIFIED BY "Oracle12c"
DEFAULT TABLESPACE "DEMODAT" TEMPORARY TABLESPACE "DEMOTMP" ACCOUNT UNLOCK;

GRANT "CONNECT" TO "DEMO";
GRANT "RESOURCE" TO "DEMO";
GRANT create session TO "DEMO";
GRANT ALTER ANY INDEX TO "DEMO";
GRANT ALTER ANY SEQUENCE TO "DEMO";
GRANT ALTER ANY TABLE TO "DEMO";
GRANT ALTER ANY TRIGGER TO "DEMO";
GRANT CREATE ANY INDEX TO "DEMO";
GRANT CREATE ANY SEQUENCE TO "DEMO";
GRANT CREATE ANY SYNONYM TO "DEMO";
GRANT CREATE ANY TABLE TO "DEMO";
GRANT CREATE ANY TRIGGER TO "DEMO";
GRANT CREATE ANY VIEW TO "DEMO";
GRANT CREATE PROCEDURE TO "DEMO";
GRANT CREATE PUBLIC SYNONYM TO "DEMO";
GRANT CREATE TRIGGER TO "DEMO";
GRANT CREATE VIEW TO "DEMO";
GRANT DELETE ANY TABLE TO "DEMO";
GRANT DROP ANY INDEX TO "DEMO";
GRANT DROP ANY SEQUENCE TO "DEMO";
GRANT DROP ANY TABLE TO "DEMO";
GRANT DROP ANY TRIGGER TO "DEMO";
GRANT DROP ANY VIEW TO "DEMO";
GRANT INSERT ANY TABLE TO "DEMO";
GRANT QUERY REWRITE TO "DEMO";
GRANT SELECT ANY TABLE TO "DEMO";
GRANT UNLIMITED TABLESPACE TO "DEMO";
GRANT CREATE JOB TO "DEMO";
GRANT CREATE ANY JOB TO "DEMO";

